#!python3
### DO IT ONCE IN CONSOLE: export PYTHONPATH=$(realpath ..)
import sys, setproctitle
from actions.tack import tack
setproctitle.setproctitle(' '.join(sys.argv))

print(' '.join(sys.argv), "begin...")
print("1st square started...")
tack(origin='Navigation', yaw=  0, dist=4.0, speed=0.5, depth=0.0)
tack(origin='Navigation', yaw= 90, dist=4.0, speed=0.5, depth=0.0)
tack(origin='Navigation', yaw=180, dist=4.0, speed=0.5, depth=0.0)
tack(origin='Navigation', yaw=270, dist=4.0, speed=0.5, depth=0.0)
print("2nd square started...")
tack(origin='Navigation', yaw=  0, dist=4.0, speed=0.5, depth=0.0)
tack(origin='Navigation', yaw= 90, dist=4.0, speed=0.5, depth=0.0)
tack(origin='Navigation', yaw=180, dist=4.0, speed=0.5, depth=0.0)
tack(origin='Navigation', yaw=270, dist=4.0, speed=0.5, depth=0.0)
print("3rd square started...")
tack(origin='Navigation', yaw=  0, dist=4.0, speed=0.5, depth=0.0)
tack(origin='Navigation', yaw= 90, dist=4.0, speed=0.5, depth=0.0)
tack(origin='Navigation', yaw=180, dist=4.0, speed=0.5, depth=0.0)
tack(origin='Navigation', yaw=270, dist=4.0, speed=0.5, depth=0.0)
print("4th square started...")
tack(origin='Navigation', yaw=  0, dist=4.0, speed=0.5, depth=0.0)
tack(origin='Navigation', yaw= 90, dist=4.0, speed=0.5, depth=0.0)
tack(origin='Navigation', yaw=180, dist=4.0, speed=0.5, depth=0.0)
tack(origin='Navigation', yaw=270, dist=4.0, speed=0.5, depth=0.0)
print(' '.join(sys.argv), "end!")
